### ISSUE TITLE
lógica da zona de armadilha em código

### ISSUE THREAD

**Issue by roddas** [SBD1/2024.1-Ben10#28]
definir a lógica da zona de armadilha em código, definir o tipo/efeito/status (enum), codar a forma que vai se comportar

**Comment by Arthrok** [comment]
no init.sql existe uma lista enumerada, inserir novos tipos lá apra a zona de armadilha, definir novos tipos porque lla tem alguns tipos que foram criados para teste. definir a nível de código os efeitos causados pelo tipo.

CREATE TYPE tipo_reducao_acrescimo AS ENUM ('redução', 'acréscimo');

redução e acrréscimo devem sumir, definir novos tipos como: reduçao de dano por determinado tempo, arrancar algum status específico de uma vez como vida e etc. Pensa em pelo menos 5 tipos novos e devem estár funcionando pra issue
